export const data = [
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: true,
    wlStage: true,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: true,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: false,
    wlStage: true,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: true,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: true,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: true,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: false,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
  {
    icon: "/waterdao.svg",
    name: "WaterDao",
    symbol: "WTD",
    hardcap: false,
    wlStage: false,
    status: "ended",
    totalRaised: "500 WETH",
    allocation: 0,
  },
];
