name: CI/CD XpandX
on:
  push:
    branches: [ master ]

jobs:
# Deploy in EC2
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy on EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /srv/XpandX-interface &&
            git checkout develop &&
            git fetch --all &&
            git reset --hard origin/develop &&
            git pull origin develop &&
            docker-compose down &&
            docker-compose  up -d --build 
          '
